### ISSUE TITLE
Local file links with starting ~ symbol in file/folder name not working

### ISSUE THREAD

**Issue by MurzNN** [feinstaub/firefox_addon_local_filesystem_links#52]
I have folders with ~ symbol (this is not a symlink, this is real symbol in file name) in Linux, for example file:///company/~Office/file.txt - they works with firefox internal functional, but when local_filesystem_links enabled - link goes not working with error: 
```
alien-local-filesystem-links
Couldn't open file: file:///company/~Office/file.txt
```
If I rename link to file:///company/test~Office/file.txt - it works
file:///company/Office/~file.txt not work too.

Can you fix this issue or descibe why this not working? Thanks!

**Comment by feinstaub** [comment]
Thanks for reporting this issue. I will have to be investigated.

**Comment by AWolf81** [comment]
I've fixed this bug. That was an issue with the ~/ links that enable a link to home directory.

Now it should work once the PR #54 is merged to master.

**Comment by MurzNN** [comment]
Seems that this is not fixed on version 0.99.42 - links with ~ not becomes working on my Ubuntu 14.04 and Firefox 44.0.2
